<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>su.nightexpress.combatpets</groupId>
        <artifactId>CombatPets</artifactId>
        <version>2.7.2</version>
    </parent>

    <artifactId>MC_26_2</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <nms.version>26.2-R0.1-20260808.232540-4</nms.version>
        <paper.version>26.2.build.112-stable</paper.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot</artifactId>
            <version>${nms.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.spigotmc</groupId>
                    <artifactId>spigot-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>${paper.version}</version>
        </dependency>

        <dependency>
            <groupId>su.nightexpress.combatpets</groupId>
            <artifactId>API</artifactId>
            <version>2.7.2</version>
        </dependency>

        <dependency>
            <groupId>su.nightexpress.combatpets</groupId>
            <artifactId>NMS</artifactId>
            <version>2.7.2</version>
        </dependency>
    </dependencies>

</project>
